build!: fix react jsx-runtime not being externalized
After Vite and Vite plugin updates in #747, lib users using Rolldown
started seeing the following client-side errors:

Error: Calling 'require' for "react" in an environment that doesn't
expose the 'require' function.

This was caused by react/jsx-runtime not being externalized during
build, which emitted dynamic requires for react even in the ESM output.

Fixed by externalizing react/jsx-runtime, and changing the output
formats from the default "es","umd" to "es","cjs" as the
"react/jsx-runtime" dependency does not have a globally named UMD
variant for us to export.

This however is a breaking change for consumers expecting to consume
Resium as an UMD build instead of CJS.